spring.application.name=MediCare

# Puerto requerido
server.port=78

# Conexion con MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/medicare
spring.datasource.username=root
spring.datasource.password=Root123!

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true