spring.application.name=MediCare

# Puerto requerido
server.port=78

# Conexion con MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/medicare
spring.datasource.username=root
spring.datasource.password=Root123!

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Configuracion de Spring Mail con Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MEDICARE_MAIL_USERNAME}
spring.mail.password=${MEDICARE_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8